### ISSUE TITLE
Will the `node.sh` script support updating with arm building?

### ISSUE THREAD

**Issue by bocheng0000** [elastos/Elastos.Node#12]
ARM architecture hosts are being used more and more. As the most popular node management tool, can `node.sh` support the update of ARM building?

**Comment by libbin** [comment]
The logic to install/update the arm64 version of the chainer is already built into the latest script.
(ela, esc, esc-oracle, eid, eid-oracle, arbiter)

Considering the preliminary nature of the current testing, users can voluntarily edit the script to enable arm64 support:
`local ENABLE_ARM64=1`

**Comment by EverlastingOS** [comment]
> The logic to install/update the arm64 version of the chainer has been built into the latest script. (ela, esc, esc-oracle, eid, eid-oracle, arbiter)
> 
> Considering the preliminary nature of the current testing, users can voluntarily edit the script to enable arm64 support: `local ENABLE_ARM64=1`

Did update on my Elabox, do get error now:
ERROR: do not support aarch64

**Comment by EverlastingOS** [comment]
> The logic to install/update the arm64 version of the chainer has been built into the latest script. (ela, esc, esc-oracle, eid, eid-oracle, arbiter)
> 
> Considering the preliminary nature of the current testing, users can voluntarily edit the script to enable arm64 support: `local ENABLE_ARM64=1`

Thanks! It works now!
